### ISSUE TITLE
item_prompt.json and user_prompt.json

### ISSUE THREAD

**Issue by jensen-srp** [HKUDS/EasyRec#1]
Hi it's great job and I really appreciate your work.
but I can't find the json files, can you provide more details?
Thx

**Comment by Re-bin** [comment]
Hi 👋!

Thank you for your interest in this work! The prompts provided in the data files correspond to the Amazon-related datasets we processed. You can obtain the datasets by using the following command:

```
wget https://archive.org/download/easyrec_data/data.zip
unzip data.zip
```

I hope the above information is helpful :)

Best regards,
Xubin
