### ISSUE TITLE
Small issue in paper

### ISSUE THREAD

**Issue by wangyu0627** [HKUDS/EasyRec#2]
At the beginning of the second paragraph in Setion 3.3, the references are cited as [40, 40].

**Comment by wangyu0627** [comment]
A great work！This should be ``train.py.''
![issue](https://github.com/user-attachments/assets/2dceaacb-238e-409a-a20a-530d44e35d04)

**Comment by Re-bin** [comment]
Hi 👋!

Many thanks for pointing out! I will update the typo soon :)

Best regards,
Xubin
